const list = [
    'Coca Cola',
    'Kraft',
    'Nestle',
    'Nescafe',
    "Kellogg's",
    'Mondelez',
    'Pepsico',
    'Mars',
    'P&G',
    'Johnson & Johnson',
    "L'oreal",
    'Iams',
    'Garnier',
    'Dawn',
    'Tide',
    'Purina',
    'Olay',
    'Cover Girl',
    'Beneful',
    'Dove',
    'Axe',
    'Unilever',
    'Oral-B',
    'Noutrogena',
    'Crest',
    'Splenda',
    'Cascade',
    'Gain',
    'Scope',
    'Tylenol',
    'Bandaid',
    'Listerene',
    'Gillette',
    'Old Spice',
    'Tampax',
    'Sudafed',
    'Bengay',
    'Duracell',
    'Pantene',
    'Pampers',
    'Braun',
    'Sour Patch',
    'Maynards',
    'Cherry Ripe',
    'Crispy Crunch',
    'Twirl',
    'Caramilk',
    'Crunchie',
    'Ritz',
    'Triscuit',
    'belVita',
    'Cheese Nips',
    'Wheat Thins',
    "Snack Well's",
    'Vitamin Water',
    'Smart Water',
    'Sprite',
    'Mezzo Mix',
    'Minute Maid',
    'Fruitopia',
    'Five Alive',
    "Barq's",
    'Fanta',
    'Nestea',
    'PowerAid',
    'Mello Yello',
    'Full Throttle',
    'Nos',
    'Looza',
    'Mirinda',
    'Brisk',
    'Ocean Spray',
    'Mug Root Beer',
    'Mountain Dew',
    'Sobe',
    'Aquafina',
    'Lipton',
    '7 Up',
    'Tropicana',
    'Pepsi',
    'Gatorade',
    'Dole',
    'Ruffles',
    'Mrs Vickies',
    'Fritos',
    'Cheetos',
    'Cracker Jack',
    'Sun Chips',
    'Tostitos',
    'Rold Gold',
    'Spitz',
    "Lay's",
    'Doritos',
    'Green Giant',
    'Hamburger Helper',
    'Betty Crocker',
    'Old El Paso',
    'Val Nature',
    'Bugles',
    'Pop Tarts',
    'Eggo',
    'Kashi',
    'Pringles',
    'Cheez-it',
    'Nutri Grain',
    'Freedent',
    '5 Gum',
    "Wrigley's",
    'Excel',
    'Doublemint',
    'Juicy Fruit',
    'Big Red',
    'Extra',
    'Hubba Bubba',
    'Orbit',
    'Trident',
    'Clorets',
    'Dentyne',
    'Stride',
    'Halls',
    'Bubblicious',
    'Chicklets',
    'Certs',
    'Oreo',
    'Nutter Butter',
    'Honey Maid',
    'Teddy Grahams',
    'Fig Newtons',
    'Nilla Wafers',
    'Chips Ahoy',
    "Cote d'Ore",
    'Green & Black Organic',
    'Toblerone',
    'Glaceau',
    'KFC',
    'Taco Bell',
    'Pizza Hut',
    'Life',
    'Aunt Jamima',
    'Crispy Minis',
    'Harvest Crunch',
    'Chewy',
    'Captain Crunch',
    'Yoplait',
    'Haagan Das',
    'Liberte',
    'Pillsbury',
    'Wanchai',
    'Corn Flakes',
    'Special K',
    'Muslix',
    'Crispix',
    'Froot Loops',
    'Bran Flakes',
    'Apple Jacks',

    'Cookie Chips',
    'Pine Cone',
    
    'Raisin Bran',
    'Corn Pops',
    'Frosted Flakes',
    'Vector',
    'Krave',
    'Rice Krispies',
    'Just Right',
    'All-bran',
    'Mini Wheats',
    'Life Savers',
    'Starburst',
    'Skittles',
    'Altoids',
    'Whiskas',
    'Pedigree',
    'Royal Canin',
    'Yum',
    'Quaker',
    'Cheerios',
    'Lucky Charms',
    'Chex',
    'Golden Grahams',
    'Cinnamon Toast Crunch',
    'Fibre 1',
    'Mars',
    'M&Ms',
    'Snickers',
    'Milky Way',
    'Dove',
    'Bounty',
    'Twix',
    'Knorr',
    'Maille',
    "Hellmann's",
    'Becel',
    'Imperial',
    'Skippy',
    'Bertolli',
    'Slimfast',
    'Pot Noodle',
    "Colman's",
    'Bovni',
    'Miracle Whip',
    'Jet Puffed',
    'Planters',
    'Jello',
    'Bullseye',
    'Cool Whip',
    'A1 Steak Sauce',
    'Cadbury',
    'Tossimo',
    'Tang',
    "Uncle Ben's",
    'Good Humor',
    'Breyers',
    'Popsicle',
    'Fudgsicle',
    "Ben & Jerry's",
    'Klondike',
    'Cornetto',
    'Magnum',
    'Salada',
    'Red Rose',
    'Lipton',
    'Dove',
    'Lever 2000',
    'St Ives',
    'Suave',
    'Noxzema',
    'Stove Top',
    "Shake 'n Bake",
    'Oscar Meyer',
    'Certo',
    'Knox',
    "Mr. Christie's",
    'Kraft Dinner',
    "Baker's",
    'David',
    'Claussen',
    'Kool-Aid',
    'Capri-Sun',
    'Crystal Light',
    'Del Monte',
    "P'tit Quebec",
    'Cheez Whiz',
    'Kraft Singles',
    'Philidelphia',
    'Polly-o',
    'Cracker Barrel',
    'Velveeta',
    'Maxwell House',
    'Nabob',
    "Stouffer's",
    'Delissio',
    'Hot Pockets',
    'Kit Kat',
    'Aero',
    'Oh Henry',
    'Rolo',
    'Coffee Crisp',
    'Crunch',
    'Smarties',
    'Goobers',
    'Butterfinger',
    'Mirage',
    'After Eight',
    'Cailler',
    'Turtles',
    'Mack',
    "Taster's Choice",
    'Nespresso',
    'Coffee-mate',
    'Perrier',
    'Nestea',
    'Pure Life',
    'S.Pellegrino',
    'Montclair',
    'Vittel',
    'Wonka',
    "L'oreal",
    'Alberto',
    'Sunsilk',
    'Thermasilk',
    'VO5',
    'Just For Me!',
    'Tresemme',
    'Close Up',
    'Pepsodent',
    'Drumstick',
    'Movenpick',
    "Dreyer's",
    'Parlour',
    'Power Bar',
    'Carnation',
    'Gerber',
    'Nesquick',
    'Chef-mate',
    'Nerds',
    'SweeTarts',
    'Laffy Taffy',
    'Runts',
    'Gobstopper',
    'Bottle Caps',
    'Garnier',
    'Vichy',
    'Biotherm',
    'The Body Shop',
    'Ombrelle',
    'Maybelline',
    "Kiehl's",
    'Dawn',
    'Tide',
    'Bounce',
    'Cascade',
    'Cheer',
    'Gain',
    'Downy',
    'Ivory',
    'Joy',
    'Mr. Clean',
    'Febreeze',
    'Swiffer',
    'Puffs',
    'Bounty',
    'Comet',
    'Oral-B',
    'Crest',
    'Scope',
    'Fixodent',
    'Pepto',
    'Vicks',
    'Metamucil',
    'Neutrogena',
    'Clean & Clear',
    'Aveeno',
    'Lubriderm',
    'Visine',
    'Nizoral',
    'Tylenol',
    'Reactine',
    'Motrin',
    'Pepcid',
    'Sudafed',
    'Imodium',
    'Polysporin',
    'Benylin',
    'Benadryl',
    'Splenda',
    'Lactaid',
    'OneTouch',
    'Listerine',
    'Reach',
    'Carefree',
    'Stayfree',
    'Nicorette',
    'NicoDerm',
    "Johnson's Baby",
    'Sunlight',
    'Vim',
    'Sun',
    'Via',
    'Breeze',
    'Q-tips',
    'Vaseline',
    'Degree',
    "Pond's",
    'Purina',
    'Beneful',
    'Cat Chow',
    'Dog Chow',
    'Friskies',
    'Fancy Feast',
    'Felix',
    'Alpo',
    'Ralph Lauren',
    'Giorgio Armani',
    'Stell McCartney',
    'Diesel',
    'Clairol',
    'Olay',
    'CoverGirl',
    'Lacoste',
    'Hugo Boss',
    'Herbal Essences',
    'Head & Shoulders',
    'Natural Instincts',
    'Pantene',
    "Nice 'n Easy",
    'Gillette',
    'Old Spice',
    'Secret',
    'Tampax',
    'Always',
    'Pampers',
    'Charmin',
    'Cushelle',
    'Duracell',
    'Pur',
    'Braun'
];
const index = {};

function search (input) {
    if (!input) {
        return list.sort();
    } else if (input in index) {
        return Array.from(index[input]).sort();
    }
    return [];
}

function addToIndex(key, value) {
    if (!(key in index)) {
        index[key] = new Set();
    }
    index[key].add(value);
}

function build() {
    list.forEach(item => {
        let cleaned = item.toLowerCase().replace(/[^a-zA-Z0-9 ]/g, '');

        for (let i = 1; i <= cleaned.length; i++) { // length of substring
            for (let j = 0; j < cleaned.length; j++) { // starting point of substring
                if (i + j > cleaned.length) { // if length + start postion is longer than the word is, we already have this key
                    break;
                }
                let key = cleaned.substring(j, j+i);
                addToIndex(key, item);
            }
        }

    });
}

function generateHTML(results) {
    return results.map(result => {
        return `<li>${result}</li>`;
    }).join('');;
}

function updatePage(html) {
    document.querySelector('#results').innerHTML = html;
}

function init() {
    build();
    let results = search('');
    let html = generateHTML(results);
    updatePage(html);

    const searcher = document.querySelector('#search');

    searcher.addEventListener('pointerup', (e => {
        e.preventDefault();
        searcher.scrollIntoView({behavior: 'smooth', block: 'start'});
    }));

    searcher.addEventListener('input', (e => {
        // debugger;
        let value = e.target.value.toLowerCase();
        let results = search(value);
        let html = generateHTML(results);
        updatePage(html);
    }));
}

exports = {
    search,
    build
};
